GPU: [1]

VERBOSE: True

MODEL:
  MODE: 'Deraining'
  SESSION: 'FDRNet'

OPTIM:
  BATCH_SIZE: 24 
  NUM_EPOCHS: 3500
  LR_INITIAL: 5e-4
  LR_MIN: 5e-7
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 5    
  RESUME: False        
  TRAIN_PS: 64
  VAL_PS: 128
  TRAIN_DIR: './Datasets/Rain200L/train'
  VAL_DIR: './Datasets/Rain200L/test'

  SAVE_DIR: './checkpoints/Rain200L'

